cd ansible/
cd roles/
ansible-galaxy role init estructura 
cd estructura/
cd tasks/
vim /home/clara/.vimrc
vim main.yml 
vim datos_alumno.txt
cd templates/
vim datos_alumno.txt
cd tasks/
vim main.yml
cd vars/
vim main.yml 
cd templates/
vim datos_alumno.txt 
vim main.yml 
cd templates/
vim datos_equipo.txt 
cd vars/
vim main.yml 
